### ISSUE TITLE
홈 페이지 공통 컴포넌트 - 블록

### ISSUE THREAD

**Issue by yoonncho** [dnd-side-project/dnd-8th-7-frontend#8]
## home 페이지에 사용될 공통 컴포넌트 구현 (블록)

- [ ] 작은 블록 컴포넌트
<img width="282" alt="image" src="https://user-images.githubusercontent.com/49135797/218297538-c1b892af-731b-43b3-84bf-853259d3f5e3.png">

- [ ] 긴 블록 컴포넌트
<img width="267" alt="image" src="https://user-images.githubusercontent.com/49135797/218297587-91016880-6952-45e1-ac3e-fd5e7f2a8c52.png">

- [ ] 펼쳤을때 task들이 보여짐
<img width="297" alt="image" src="https://user-images.githubusercontent.com/49135797/218297631-4d8a758f-19fd-4ad2-a5a9-ea126b9bf6e2.png">
=> task 추가 및 체크 가능

**Comment by eun-seong** [comment]
![image](https://user-images.githubusercontent.com/49540564/219872920-694e5303-8188-4322-a095-d837abeac840.png)


이 블록도 포함할 수 있도록 기다란 Block 컴포넌트를 구현하면 좋을 것 같아요.
expandable을 prop으로 넘겨서 펼쳤을 때 렌더링할 노드를 넘기면 될 것 같습니다.
